####################
##      CORE  	  ##
####################
[Core]
description = "Core packages I use daily"

[Core.bat]
description = "A cat clone with wings."
url = "https://github.com/sharkdp/bat"
apt = "bat"
brew = "bat"
dnf = "bat"
pacman = "bat"

[Core.cURL]
description = "A command line tool for transferring data with URL syntax."
url = "https://curl.se/"
apt = "curl"
brew = "curl"
dnf = "curl"
pacman = "curl"

[Core.exa]
description = "A modern replacement for ls."
url = "https://the.exa.website/"
apt = "exa"
brew = "exa"
dnf = "exa"
pacman = "exa"

[Core.fd]
description = "A simple, fast and user-friendly alternative to find."
url = "https://github.com/sharkdp/fd"
apt = "fd-find"
brew = "fd"
dnf = "fd-find"
pacman = "fd"

[Core.fzf]
description = "A command-line fuzzy finder."
url = "https://github.com/junegunn/fzf"
apt = "fzf"
brew = "fzf"
dnf = "fzf"
pacman = "fzf"

[Core.git]
description = "A fast, scalable, distributed revision control system."
url = "https://git-scm.com/"
apt = "git"
brew = "git"
dnf = "git"
pacman = "git"

[Core.GnuPG]
description = "A complete and free implementation of the OpenPGP standard."
url = "https://gnupg.org/"
apt = "gnupg"
brew = "gnupg"
dnf = "gnupg"
pacman = "gnupg"

[Core.Node]
description = "A JavaScript runtime built on Chrome's V8 JavaScript engine."
url = "https://nodejs.org/"
apt = "nodejs"
brew = "node"
dnf = "nodejs"
pacman = "nodejs"

[Core."Oh My Zsh"]
description = "A delightful community-driven framework for managing your zsh configuration."
install_command = "sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\" \"\" --unattended"

[Core.OpenSSL]
description = "A robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols."
url = "https://www.openssl.org/"
apt = "openssl"
brew = "openssl"
dnf = "openssl"
pacman = "openssl"

[Core.ripgrep]
description = "A line-oriented search tool that recursively searches your current directory for a regex pattern."
url = "https://github.com/BurntSushi/ripgrep"
apt = "ripgrep"
brew = "ripgrep"
dnf = "ripgrep"
pacman = "ripgrep"

[Core.tmux]
description = "A terminal multiplexer."
url = "https://github.com/tmux/tmux"
apt = "tmux"
brew = "tmux"
dnf = "tmux"
pacman = "tmux"

[Core.Vim]
description = "A highly configurable text editor built to enable efficient text editing."
url = "https://www.vim.org/"
apt = "vim"
brew = "vim"
dnf = "vim"
pacman = "vim"

[Core.Zsh]
description = "A shell designed for interactive use, although it is also a powerful scripting language."
url = "https://www.zsh.org/"
apt = "zsh"
brew = "zsh"
dnf = "zsh"
pacman = "zsh"


####################
##     DESIGN  	  ##
####################
[Design.FFmpeg]
description = "A complete, cross-platform solution to record, convert and stream audio and video."
url = "https://ffmpeg.org/"
apt = "ffmpeg"
brew = "ffmpeg"
dnf = "ffmpeg-free"
pacman = "ffmpeg"


####################
##    GUI CORE 	  ##
####################
["GUI Core"."Clean My Mac"]
description = "A macOS app to clean up your Mac."
url = "https://macpaw.com/cleanmymac"
brew = "--cask cleanmymac"

["GUI Core".Dropbox]
description = "A file hosting service that offers cloud storage, file synchronization, personal cloud."
url = "https://www.dropbox.com/"
brew = "--cask dropbox"

["GUI Core"."Docker Desktop"]
description = "A desktop app for MacOS and Windows machines for the building and sharing of containerized applications and microservices."
url = "https://www.docker.com/products/docker-desktop"
brew = "--cask docker"

["GUI Core".IINA]
description = "The modern video player for macOS."
url = "https://iina.io/"
brew = "--cask iina"

["GUI Core".iTerm2]
description = "A terminal emulator for macOS that does amazing things."
url = "https://iterm2.com/"
brew = "--cask iterm2"

["GUI Core"."Little Snitch"]
description = "A firewall application for macOS that monitors outgoing network connections and allows or denies them."
url = "https://www.obdev.at/products/littlesnitch/index.html"
brew = "--cask little-snitch"

["GUI Core"."Mullvad VPN"]
description = "A VPN service that helps keep your online activity, identity, and location private."
url = "https://mullvad.net/en/"
brew = "--cask mullvadvpn"

["GUI Core"."Parallels Desktop"]
description = "A software for running Windows, Linux, or any other operating system on a Mac without rebooting."
url = "https://www.parallels.com/products/desktop/"
brew = "--cask parallels"

["GUI Core".Raycast]
description = "A smart command line productivity tool for macOS."
url = "https://raycast.com/"
brew = "--cask raycast"

["GUI Core".Zoom]
description = "A video conferencing, online chat, and web conferencing software."
url = "https://zoom.us/"
brew = "--cask zoomus"


####################
##   GUI DESIGN	  ##
####################
["GUI Design"."Adobe Creative Cloud"]
description = "A collection of desktop and mobile apps and services for photography, design, video, web, UX and more."
url = "https://www.adobe.com/creativecloud.html"
brew = "--cask adobe-creative-cloud"

["GUI Design".Glyphs]
description = "A powerful font editor for macOS."
url = "https://glyphsapp.com/"
brew = "--cask glyphs"

["GUI Design"."Rhino 3D"]
description = "A 3D modeling software for Windows, macOS, and Linux."
url = "https://www.rhino3d.com/"
brew = "--cask rhino"

["GUI Design"."cycling ‘74 Max/MSP"]
description = "A visual programming language for music, audio, and multimedia."
url = "https://cycling74.com/products/max/"
brew = "--cask cycling74-max"
